### ISSUE TITLE
jQuery Animated Scrolling will not work.

### ISSUE THREAD

**Issue by dotgodly** [timcreative/light-bootstrap-dashboard#11]
I've added
```
<script type="text/javascript>
 $('p').click(function(){
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
});
</script>
```
to the bottom of dashboard.html, with no luck at all.

Putting `$("html, body").animate({ scrollTop: 0 }, 600);` into the console also does nothing.

**Comment by alexandru-paduraru** [comment]
@dotgodly the body of our product has a fixed height of 100% of the screen, that means the scroll is done inside the .main-panel div. So to achieve the scroll please apply the animation to .main-panel like in this example:

    $(".main-panel").animate({ scrollTop: 0 }, 2000);

Then it will work fine.

Best,
Alex

**Comment by dotgodly** [comment]
Thanks for the help!
