### ISSUE TITLE
SCSS Version

### ISSUE THREAD

**Issue by onlymejosh** [timcreative/light-bootstrap-dashboard#3]
Really like the look of this but wanted to know when you're going to be releasing the SCSS version

**Comment by alexandru-paduraru** [comment]
It will be released in the first week of October in parallel with Light Bootstrap Dashboard PRO. Stay tuned!

**Comment by prabowomurti** [comment]
Hi, will you also include the Login Page on the next release ?

**Comment by alexandru-paduraru** [comment]
@prabowomurti the Login Page/Register Page/ Lock Page and other features will be included in the PRO version (which will be released ASAP).

**Comment by jitendravyas** [comment]
i'm also waiting for Sass version

**Comment by alexandru-paduraru** [comment]
Hi, after all the requests we added the Sass version here too, hope it will be useful.
