### ISSUE TITLE
Could you add an login/register page?

### ISSUE THREAD

**Issue by su-xiaolin** [timcreative/light-bootstrap-dashboard#4]

**Comment by alexandru-paduraru** [comment]
Hi @su-xiaolin! Thank you for your interest in our product. We have (Login)[http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/pages/login.html], (Register)[http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/pages/register.html], (Lock Screen)[http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/pages/lock.html] pages and many other useful examples in (Light Bootstrap Dashboard PRO)[http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/dashboard.html]. You can grab your copy with 50% Black friday discount on (www.creative-tim.com)[http://www.creative-tim.com]
