### ISSUE TITLE
PSD Available? for PRO Version 69$ one

### ISSUE THREAD

**Issue by arunshourie** [timcreative/light-bootstrap-dashboard#5]
Hi,

I recently bought this and doesn't seem to have 

1. fonts used in sketch
2. Can we have PSDs? please! please! please!

we're developing a very good platform and also will give you credits!. 
our designers are comfortable with PSDs...

Thanks,
Arun

**Comment by alexandru-paduraru** [comment]
@arunshourie thank you for being our customer. We also responded you on [Creative Tim](http://www.creative-tim.com/product/light-bootstrap-dashboard-pro?page=4#comment-924). We added the fonts in v1.1.1 and you can download it from your dashboard on Creative-Tim.com. Unfortunately, we don't have a Photoshop version of LBD Pro, it was designed using Sketch. If there will be more requests for Photoshop we will create that version too.

Please send us a link when you finish with the development, we would like to promote your platform in our gallery.

All the best,
Alex
